version: '3'
services:
  web1:
    build:
      context: ./frontend
    container_name: web_app_server1
    ports:
      - "8081:80"
    environment:
      - SERVER_COLOR=red  # Servidor 1 en rojo

  web2:
    build:
      context: ./frontend
    container_name: web_app_server2
    ports:
      - "8082:80"
    environment:
      - SERVER_COLOR=green  # Servidor 2 en verde

  web3:
    build:
      context: ./frontend
    container_name: web_app_server3
    ports:
      - "8083:80"
    environment:
      - SERVER_COLOR=blue  # Servidor 3 en azul

  web4:
    build:
      context: ./frontend
    container_name: web_app_server4
    ports:
      - "8084:80"
    environment:
      - SERVER_COLOR=yellow  # Servidor 4 en amarillo

  nginx:
    image: nginx:latest
    container_name: nginx_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3
      - web4